name: Deploy application to VM

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      port:
        required: true
        type: string
    secrets:
      ssh_key:
        required: true
      host:
        required: true
      supabase_url:
        required: true
      supabase_key:
        required: true

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.ssh_key }}" > ~/.ssh/vm
          chmod 600 ~/.ssh/vm
          ssh-keyscan -p 22 -t ed25519 ${{ secrets.host }} >> ~/.ssh/known_hosts

      - name: Stop the app and clean up
        run: |
          ssh -i ~/.ssh/vm "ubuntu@${{ secrets.host }}" << END
            screen -XS auspak_${{ inputs.port }} quit
            rm -rf ~/auspak_${{ inputs.port }}
            mkdir ~/auspak_${{ inputs.port }}
          END

      - name: Push repo to the host
        run: |
          scp -i ~/.ssh/vm -r ./* "ubuntu@${{ secrets.host }}:/home/ubuntu/auspak_${{ inputs.port }}"

      - name: Set up dependencies
        run: |
          ssh -i ~/.ssh/vm "ubuntu@${{ secrets.host }}" << END
            python3.9 -m venv ~/auspak_${{ inputs.port }}/venv
            source ~/auspak_${{ inputs.port }}/venv/bin/activate
            python3.9 -m pip install --upgrade pip
            pip install -r ~/auspak_${{ inputs.port }}/requirements.txt
          END

      - name: Run the app
        run: |
          ssh -i ~/.ssh/vm "ubuntu@${{ secrets.host }}" << END
            export SUPABASE_URL=${{ secrets.supabase_url }}
            export SUPABASE_KEY=${{ secrets.supabase_key }}
            screen -s "/bin/bash" -dmS auspak_${{ inputs.port }}
            screen -S auspak_${{ inputs.port }} -X stuff "source ~/auspak_${{ inputs.port }}/venv/bin/activate\n"
            screen -S auspak_${{ inputs.port }} -X stuff "python3.9 ~/auspak_${{ inputs.port }}/app.py --port ${{ inputs.port }}\n"
          END
