name: Deploy to Oracle Cloud Infrastructure

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.ORACLE_SSH_KEY }}" > ~/.ssh/oracle
          chmod 600 ~/.ssh/oracle
          ssh-keyscan -p 22 -t ed25519 ${{ secrets.ORACLE_HOST }} >> ~/.ssh/known_hosts

      - name: Stop the app and clean up
        run: |
          ssh -i ~/.ssh/oracle "ubuntu@${{ secrets.ORACLE_HOST }}" -f << END
            screen -XS auspak quit
            rm -rf ~/auspak
            mkdir ~/auspak
          END

      - name: Push repo to the host
        run: |
          scp -i ~/.ssh/oracle -r ./ "ubuntu@${{ secrets.ORACLE_HOST }}:/home/ubuntu/auspak"

      - name: Set up dependencies
        run: |
          ssh -i ~/.ssh/oracle "ubuntu@${{ secrets.ORACLE_HOST }}" -f << END
            python3 -m venv ~/auspak/venv
            source ~/auspak/venv/bin/activate
            python3 -m pip install --upgrade pip
            pip install -r ~/auspak/requirements.txt
          END
