name: Action on new commits to PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy-to-dev:
    uses: ./.github/workflows/deploy-to-vm.yml
    with:
      environment: development
      port: 8001
    secrets:
      ssh_key: ${{ secrets.ORACLE_SSH_KEY }}
      host: ${{ secrets.ORACLE_HOST }}
      supabase_url: ${{ secrets.SUPABASE_URL }}
      supabase_key: ${{ secrets.SUPABASE_KEY }}
      graphhopper_api_key: ${{ secrets.GRAPHOPPER_API_KEY }}
  run-linter:
    name: Run linter
    runs-on: ubuntu-latest
    needs: [deploy-to-dev]

    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Run Pylint
        run: |
          pylint ./ --disable=C0103
