name: Action on PR push to main

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-to-prod:
    uses: ./.github/workflows/deploy-to-vm.yml
    with:
      environment: production
      port: 8000
    secrets:
      ssh_key: ${{ secrets.ORACLE_SSH_KEY }}
      host: ${{ secrets.ORACLE_HOST }}
      supabase_url: ${{ secrets.SUPABASE_URL }}
      supabase_key: ${{ secrets.SUPABASE_KEY }}
