name: Action on PR push to main

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-to-prod:
    uses: ./.github/workflows/deploy-to-vm.yml
    name: Deploy to prod environment
    with:
      environment: production
      port: 8000
    secrets:
      vm_ssh_key: ${{ secrets.VM_SSH_KEY }}
      vm_host: ${{ secrets.VM_HOST }}
      vm_user: ${{ secrets.VM_USER }}
      vm_home_path: ${{ secrets.VM_HOME_PATH }}
      supabase_url: ${{ secrets.SUPABASE_URL }}
      supabase_key: ${{ secrets.SUPABASE_KEY }}
      graphhopper_api_key: ${{ secrets.GRAPHOPPER_API_KEY }}
